### ISSUE TITLE
Question about using scriptcwl

### ISSUE THREAD

**Issue by vinay-is** [NLeSC/scriptcwl#104]
I have a requirement where i need to create generic workflows using pre-defined steps. 

So taking an example in this package documentation I have 2 workflow steps "Add" and "Multiply"

Now I want to create workflows like these  
a) Worflow1 : add, multiply, add, multiply
b) Workflow2 : add, add, add, multiply, add, add

So I want to write a generic function using which I can create these generic worflows. So this function will take the worflow_steps as inputs and then cascade them to create a workflow. So I want to know is this possible using this package.

**Comment by jvdzwaan** [comment]
Yes, that is possible. You could do something like:

```
with WorkflowGenerator() as wf:
    wf.load(steps_dir='/path/to/scriptcwl/scriptcwl/examples/')
    
    num1 = wf.add_input(num1='int')
    num2 = wf.add_input(num2='int')
    
    steps = ['add', 'multiply', 'add', 'multiply']

    x = num1
    y = num2
    
    for s in steps:
        if s == 'add':
            answer = wf.add(x=x, y=y)
            x = answer
        elif s == 'multiply':
            answer = wf.multiply(x=x, y=y)
            x = answer
```

You could even do:

```
answer = wf.__getattr__('add', x=num1, y=num2)()
```
If you want to get rid of the ifs.

The trick is keeping track of the inputs and outputs and connecting them in the correct way.
