### ISSUE TITLE
Order of workflow inputs is sometimes incorrect

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/scriptcwl#11]
If you run:
```
import nlppln
from nlppln import WorkflowGenerator

wf = WorkflowGenerator()

dir_in, skip = wf.add_inputs(dir_in='Directory', skip='string?')
```

`dir_in` has the value of `skip` and  `skip` the value of `dir_in`

**Comment by jvdzwaan** [comment]
This is addressed in the documentation of `WorkflowGenerator`:

`addd_inputs` method returns a list of strings containing the names that
    can be used to connect these input parameters to step input parameter
    names. (Please note that because **kwargs are unordered, the list of input
    names may not be in the same order as the **kwargs. When a workflow has
    multiple inputs, it is probably safer to call `add_inputs` for every
    parameter separately.)

Perhaps it should also be mentioned in the README.

**Comment by LourensVeen** [comment]
Maybe it should return a dictionary? Then you could write
```inputs = wf.add_inputs(dir_in='Directory', skip='string?')'''
and use `inputs['dir_in']` to refer to that input?

**Comment by bouweandela** [comment]
Solution: Janneke decided that the method should be changed to `add_input`.
