### ISSUE TITLE
Importing WorkflowGenerator from scriptcwl does not work

### ISSUE THREAD

**Issue by michaelbenayoun** [NLeSC/scriptcwl#115]
When trying to import WorkflowGenerator (from scriptcwl import WorkflowGenerator) I get "cannot import name validate_document".

I tried on a clean environment with python 2.7 and python 3, both failed.
Initially, I was trying to run the ICDAR2017_shared_task_workflows notebook from ochre

**Comment by jvdzwaan** [comment]
I fixed that last week! If you install the development version (so, cloning the repository, and not using pip), it should work.

**Comment by michaelbenayoun** [comment]
Thanks a lot !
