### ISSUE TITLE
Load step from url

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/scriptcwl#34]
Currently, only steps from the local file system can be loaded into the steps library. Scriptcwl should also be able to load steps from urls.

**Comment by bldevries-escience** [comment]
For single files http/https urls can already be used like, for example, this:
wf.load(step_file="https://raw.githubusercontent.com/WhatWorksWhenForWhom/nlppln/develop/cwl/anonymize.cwl")
This functionality was already implemented in cwltool.load_tool.fetch_document
