### ISSUE TITLE
How to save workflows with steps from multiple directories?

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/scriptcwl#38]
I usually work with generic vs. project specific cwl steps that are loaded from different directories, for example https://github.com/WhatWorksWhenForWhom/nlppln and https://github.com/KBNLresearch/ochre. How to make sure workflows that use steps from multiple directories can be run on different computers? 

Packed workflows may be the best solution.

This is issue is related to #25

**Comment by atzeus** [comment]
Using inline workflow. Currently we cannot remove the `#!/usr/bin/env cwl-runner` comments in the middle of the files. See https://bitbucket.org/ruamel/yaml/issues/31/provide-a-way-to-get-the-comment-string

**Comment by atzeus** [comment]
The inline files will get long id's and extra info, this is a bug in cwltool(?)

 https://github.com/common-workflow-language/cwltool/issues/564

**Comment by atzeus** [comment]
Works now (from commit b487ef58df2a19575c7528c01300380a3d4ac0c1) by giving inline=True to save (default false). Issues mentioned above, may get resolved in later versions of ruamel and cwltool

**Comment by LourensVeen** [comment]
Fixed the shebang issue by digging into ruamel deeper, and the id's can be fixed by manually giving them local JSON-LD IRIs, so that cwltool doesn't add file:// IRIs. Both a bit ugly, but it worked (I added a test case too).
