### ISSUE TITLE
Figure out cwl-runner (and add to documentation)

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/scriptcwl#57]
We replaced cwl-runner in the shebang with cwltool. However, this is not a sustainable solution, as users may want to use a different cwl implementation than cwltool. So, we need to figure out how to set cwl-runner and add this to the documentation.

**Comment by bouweandela** [comment]
From https://github.com/common-workflow-language/cwltool/blob/master/README.rst:
"Remember, if co-installing multiple CWL implementations then you need to maintain which implementation `cwl-runner` points to via a symbolic file system link or another facility."

I think we should simply put `cwl-runner` in the shebang line and leave it up to the user to define a symlink pointing to their actual cwl runner, e.g. by manually creating a symlink and adding it to their `$PATH` variable or using the linux [alternatives](https://linux.die.net/man/8/update-alternatives) system.
